description = "KotlinJS project for browser"

[args]
wrapper = { description = "Gradle wrapper version", default = "7.3.3" }
kotlin = { description = "Kotlin version", default = "1.7.10" }

[[files]]
path = "src/test/kotlin/$(package)/SimpleTest.kt"
content = """package $(package)

import kotlin.test.Test
import kotlin.test.assertEquals

class TestClient {
    @Test
    fun testGreet() {
        assertEquals("world", greet())
    }
}
"""

[[files]]
path = "src/main/kotlin/$(package)/Simple.kt"
content = """package $(package)

fun main() {
    console.log("Hello, ${greet()}")
}

fun greet() = "world"
"""

[[files]]
path = "src/main/resources/index.html"
content = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>JS Client</title>
</head>
<body>
<script src="$(artifact).js"></script>
</body>
</html>
"""

[[files]]
path = "settings.gradle.kts"
content = """
rootProject.name = "$(artifact)"

// https://twitter.com/Louis_CAD/status/1498270951175299080?s=20&t=uv0XxtYQzbktJTcpvnJ6Wg
rootDir.resolve("gradle.properties").copyTo(
    target = rootDir.resolve("buildSrc/gradle.properties"),
    overwrite = true,
)
"""

[[files]]
path = "build.gradle.kts"
content = """plugins {
    kotlin("js") version Versions.kotlin
}

group = "$(group)"
version = "$(version)"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(kotlin("test"))
}

kotlin {
    js(IR) {
        binaries.executable()
        browser {
            commonWebpackConfig {
                cssSupport.enabled = true
            }
        }
    }

    rootProject.plugins.withType<org.jetbrains.kotlin.gradle.targets.js.yarn.YarnPlugin> {
        // Download Node and Yarn only in CI environment.
        val isCI = !System.getenv("CI_ENV").isNullOrEmpty()
        rootProject.the<org.jetbrains.kotlin.gradle.targets.js.yarn.YarnRootExtension>().download = isCI
        rootProject.the<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension>().download = isCI
    }
}
"""

[[files]]
path = "buildSrc/src/main/kotlin/Versions.kt"
content = """object Versions {
    const val kotlin = "$(kotlin)"
}
"""

[[files]]
path = "buildSrc/settings.gradle.kts"
content = """rootProject.name = "buildSrc"
"""

[[files]]
path = "buildSrc/build.gradle.kts"
content = """plugins {
    `kotlin-dsl`
}

repositories {
    mavenCentral()
}
"""

[[files]]
path = "gradle/wrapper/gradle-wrapper.properties"
content = """distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-$(wrapper)-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
"""

[[files]]
path = "gradle.properties"
content = """kotlin.code.style=official
kotlin.js.generate.executable.default=false
"""

