description = "Multi-projects project using Kotlin language"

[args]
subproject = { description = "Name of the subproject, should be different from the artifact" }
wrapper = { description = "Gradle wrapper version", default = "7.3.3" }
targetJvm = { default = "17" }
kotlin = { description = "Kotlin version", default = "1.7.10" }

[[files]]
path = "gradle/wrapper/gradle-wrapper.properties"
content = """distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-$(wrapper)-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
"""

[[files]]
path = "$(subproject)/build.gradle.kts"
content = """import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm")
}

dependencies {
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

java {
    sourceCompatibility = JavaVersion.VERSION_$(targetJvmJava)
    targetCompatibility = JavaVersion.VERSION_$(targetJvmJava)
}
tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "$(targetJvm)"
}
"""

[[files]]
path = "buildSrc/build.gradle.kts"
content = """plugins {
    `kotlin-dsl`
}

repositories {
    mavenCentral()
}
"""

[[files]]
path = "buildSrc/settings.gradle.kts"
content = """rootProject.name = "buildSrc"
"""

[[files]]
path = "buildSrc/gradle.properties"
content = """kotlin.code.style=official
"""

[[files]]
path = "buildSrc/src/main/kotlin/Versions.kt"
content = """object Versions {
    const val kotlin = "$(kotlin)"
}"""

[[files]]
path = "build.gradle.kts"
content = """plugins {
    kotlin("jvm") version Versions.kotlin apply false
}

group = "$(group)"
version = "$(version)"

allprojects {
    repositories {
        mavenCentral()
    }
}
"""

[[files]]
path = "settings.gradle.kts"
content = """rootProject.name = "$(artifact)"

include("$(subproject)")

// https://twitter.com/Louis_CAD/status/1498270951175299080?s=20&t=uv0XxtYQzbktJTcpvnJ6Wg
rootDir.resolve("gradle.properties").copyTo(
    target = rootDir.resolve("buildSrc/gradle.properties"),
    overwrite = true,
)
"""

[[files]]
path = "gradle.properties"
content = """kotlin.code.style=official
"""

[[files]]
path = "$(subproject)/src/test/kotlin/$(packagePath)/SimpleTest.kt"
content = """package $(package)

import kotlin.test.*

class SimpleTest {
    @Test
    fun test() {
        assertEquals(1, 1)
    }
}"""

[[files]]
path = "$(subproject)/src/main/kotlin/$(packagePath)/main.kt"
content = """package $(package)

fun main() {
    println("Hello, world!")
}"""

