description = "Single project"

[args]
wrapper = { description = "Gradle wrapper version", default = "7.3.3" }
targetJvm = { default = "17" }
junitJupiter = { description = "junitJupiter version", default = "5.8.1" }

[[files]]
path = "gradle/wrapper/gradle-wrapper.properties"
content = """distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-$(wrapper)-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists"""

[[files]]
path = "buildSrc/build.gradle.kts"
content = """plugins {
    `kotlin-dsl`
}

repositories {
    mavenCentral()
}
"""

[[files]]
path = "buildSrc/settings.gradle.kts"
content = """rootProject.name = "buildSrc"
"""

[[files]]
path = "buildSrc/src/main/kotlin/Versions.kt"
content = """object Versions {
    const val junitJupiter = "$(junitJupiter)"
}"""

[[files]]
path = "build.gradle.kts"
content = """plugins {
    id("java")
}

group = "$(group)"
version = "$(version)"

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_$(targetJvmJava)
    targetCompatibility = JavaVersion.VERSION_$(targetJvmJava)
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:${Versions.junitJupiter}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${Versions.junitJupiter}")
}

tasks.getByName<Test>("test") {
    useJUnitPlatform()
}"""

[[files]]
path = "gradle.properties"
content = """"""

[[files]]
path = "settings.gradle.kts"
content = """rootProject.name = "$(artifact)"

// https://twitter.com/Louis_CAD/status/1498270951175299080?s=20&t=uv0XxtYQzbktJTcpvnJ6Wg
rootDir.resolve("gradle.properties").copyTo(
    target = rootDir.resolve("buildSrc/gradle.properties"),
    overwrite = true,
)
"""

[[files]]
path = "src/test/java/$(packagePath)/TestExample.java"
content = """package $(package);
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class TestExample {
    @Test
    public void test() {
        assertEquals(1, 1);
    }
}
"""

[[files]]
path = "src/main/java/$(packagePath)/Main.java"
content = """package $(package);

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
"""
